_BASE_: Base-Cityscapes-PanopticSegmentation.yaml
_BASE_: maskformer2_R50_bs16_90k.yaml

MODEL:
  BACKBONE:
    NAME: "build_resnet_backbone"
  WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"
  PIXEL_MEAN: [123.675, 116.280, 103.530, 100]
  PIXEL_STD: [58.395, 57.120, 57.375, 50]
DATASETS:
  TRAIN: ("cityscapes_fine_depth_panoptic_train",)
  TEST: ("cityscapes_fine_depth_panoptic_val",)

